layout_spectrum: 0.2493734
typography_spectrum: 0.2713033
color:
  saturation: 0.358396
  brandStrength: 0.2841276
  lightness: 0.8994077
  rhythmicContrast: 0.7437344
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: See Me After...
